import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ]

  docSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [{ type: 'autogenerated', dirName: 'intro' }]
    },
    {
      type: 'category',
      label: 'Specification',
      items: [{ type: 'autogenerated', dirName: 'spec' }]
    }
  ],
  // Make the default Docusaurus tutorial not a part of the main sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Docusaurus Tutorial',
      items: [{ type: 'autogenerated', dirName: 'docusaurus' }]
    }
  ]
};

export default sidebars;
