name: Deploy PR to Github Pages

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        if: github.event.action != 'closed'
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci --ignore-scripts
      - name: Build website
        if: github.event.action != 'closed'
        env:
          BASE_URL: /nr-pies/pr-preview/pr-${{ github.event.pull_request.number }}
        run: npm run build
      - name: Deploy to/Cleanup GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
